### ISSUE TITLE
Refresh 2024 Tech Radar

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [moj-analytical-services/data-and-analytics-engineering-tech-radar#153]
- [x] Split up data and analytics engineers into 5 teams led by 5 leads

@dami-moj :
- [x] Ensure there are at most 125 discussions which are open and have one of the 4 recognised labels
- [x] Ensure all the discussions have a label or are closed e.g. Analytics Engineers
- [x] Ensure that everyone who didn't attend has reviewed at least one of the categories

@murad-ali-MoJ 
- [x] Ensure that similar technologies/techniques are placed in the same category e.g. pulumi and terraform
- [x] Ensure that all technology/technique have a link is on the description, (not in a comment)
- [ ] https://github.com/moj-analytical-services/data-and-analytics-engineering-tech-radar/pull/357
- [ ] https://github.com/ministryofjustice/data-and-analytics-engineering/issues/33

**Comment by murad-ali-MoJ** [comment]
I was not able to get the link for these two blips- Acceptance Criteria and
Show and tells
